# Generated by Django 5.1.4 on 2024-12-30 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyimage',
            old_name='associated_property',
            new_name='property',
        ),
    ]
