# Generated by Django 5.1.4 on 2025-01-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_rename_associated_property_propertyimage_property'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['-id']},
        ),
    ]
